"""Make machine code bytes directly callable from Python via ctypes.

The generated x86-64 bytes are copied into a read/write/execute memory
region (allocated with ``mmap``) and wrapped in a ``ctypes.CFUNCTYPE``
function pointer.  The resulting object behaves like a normal Python
callable that accepts and returns 64-bit signed integers.

All functions generated by the Telos compiler use the System V AMD64 ABI
(Linux / macOS):
* Up to 6 integer parameters: RDI, RSI, RDX, RCX, R8, R9
* Return value in RAX (returned as a Python ``int`` via ``c_int64``)
"""

from __future__ import annotations

import ctypes
import mmap
from typing import Callable


class NativeFunction:
    """A callable backed by native x86-64 machine code.

    Parameters
    ----------
    code : bytes
        Raw x86-64 machine code bytes.
    n_params : int
        Number of 64-bit integer parameters.

    Attributes
    ----------
    code : bytes
        The machine code bytes that were compiled.
    """

    def __init__(self, code: bytes, n_params: int) -> None:
        self.code = code
        self._n_params = n_params
        self._mem, self._callable = _make_callable(code, n_params)

    def __call__(self, *args):
        return self._callable(*args)

    def __repr__(self) -> str:
        return (
            f"<NativeFunction n_params={self._n_params} "
            f"code_size={len(self.code)} bytes>"
        )


def _make_callable(code: bytes, n_params: int):
    """Allocate RWX memory, write *code* into it, and return a ctypes callable.

    Returns
    -------
    (mem, fn)
        *mem* is the ``mmap`` object — it must be kept alive as long as *fn*
        is in use.  *fn* is the ctypes function pointer.
    """
    size = max(len(code), 1)

    # Allocate anonymous read/write/execute memory
    mem = mmap.mmap(
        -1,
        size,
        prot=mmap.PROT_READ | mmap.PROT_WRITE | mmap.PROT_EXEC,
    )
    mem.write(code)
    mem.seek(0)

    # Create a ctypes buffer pointing into the mmap region
    buf = (ctypes.c_char * size).from_buffer(mem)
    addr = ctypes.addressof(buf)

    # Build the ctypes function type: all params and return value are int64
    param_types = [ctypes.c_int64] * n_params
    ftype = ctypes.CFUNCTYPE(ctypes.c_int64, *param_types)
    fn = ftype(addr)

    # Attach memory anchors to fn so the GC cannot collect them
    fn._mem = mem
    fn._buf = buf

    return mem, fn
